# Generated by Django 5.0.3 on 2024-03-12 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=100)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status", models.PositiveSmallIntegerField()),
                ("address", models.CharField(blank=True, max_length=20)),
                ("exec_time", models.IntegerField(null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("error_messages", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
